name: ordreset
dependencies:
  angular: ^4.0.0
  angular_components: ^0.8.0
  collection: ^1.14.0
  http: ^0.11.0
  intl: ^0.15.0
  pub:
    git: https://github.com/dart-lang/pub.git
  xml: ^2.6.0
dev_dependencies:
  angular_test: ^1.0.0
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.0
  test: ^0.12.0
transformers:
- angular:
    entry_points:
    - web/main.dart
    - test/**_test.dart
- test/pub_serve:
    $include: test/**_test.dart
- dart_to_js_script_rewriter
